//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FELCOM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FELCOM\\")]
        public string CarpetaRaiz {
            get {
                return ((string)(this["CarpetaRaiz"]));
            }
            set {
                this["CarpetaRaiz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FELCOM\\Procesados\\")]
        public string CarpetaProcesados {
            get {
                return ((string)(this["CarpetaProcesados"]));
            }
            set {
                this["CarpetaProcesados"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FELCOM\\Errores\\")]
        public string CarpetaErrores {
            get {
                return ((string)(this["CarpetaErrores"]));
            }
            set {
                this["CarpetaErrores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FELCOM\\Respuesta\\")]
        public string CarpetaRespuestas {
            get {
                return ((string)(this["CarpetaRespuestas"]));
            }
            set {
                this["CarpetaRespuestas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TiempoSegundosEscaneo {
            get {
                return ((int)(this["TiempoSegundosEscaneo"]));
            }
            set {
                this["TiempoSegundosEscaneo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string URLWS {
            get {
                return ((string)(this["URLWS"]));
            }
            set {
                this["URLWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsuarioWS {
            get {
                return ((string)(this["UsuarioWS"]));
            }
            set {
                this["UsuarioWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PassWS {
            get {
                return ((string)(this["PassWS"]));
            }
            set {
                this["PassWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CuentaCorreo {
            get {
                return ((string)(this["CuentaCorreo"]));
            }
            set {
                this["CuentaCorreo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsuarioCorreo {
            get {
                return ((string)(this["UsuarioCorreo"]));
            }
            set {
                this["UsuarioCorreo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PassCorreo {
            get {
                return ((string)(this["PassCorreo"]));
            }
            set {
                this["PassCorreo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServidorSMTP {
            get {
                return ((string)(this["ServidorSMTP"]));
            }
            set {
                this["ServidorSMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PuertoSMTP {
            get {
                return ((string)(this["PuertoSMTP"]));
            }
            set {
                this["PuertoSMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int PeticionesParalelas {
            get {
                return ((int)(this["PeticionesParalelas"]));
            }
            set {
                this["PeticionesParalelas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pruebassalvador.ekomercio.com/WSFEBuilderSV_GLOBALIMENTOS/WSFEBuilderSV.as" +
            "mx")]
        public string FELCOM_ekomercio_WSFEBuilder {
            get {
                return ((string)(this["FELCOM_ekomercio_WSFEBuilder"]));
            }
            set {
                this["FELCOM_ekomercio_WSFEBuilder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FELCOM\\Procesando\\")]
        public string CarpetaProcesando {
            get {
                return ((string)(this["CarpetaProcesando"]));
            }
            set {
                this["CarpetaProcesando"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EscanerSwitch {
            get {
                return ((bool)(this["EscanerSwitch"]));
            }
            set {
                this["EscanerSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FELCOM\\ToPrinter\\")]
        public string CarpetaToPrinter {
            get {
                return ((string)(this["CarpetaToPrinter"]));
            }
            set {
                this["CarpetaToPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FELCOM\\Impresos\\")]
        public string CarpetaImpresos {
            get {
                return ((string)(this["CarpetaImpresos"]));
            }
            set {
                this["CarpetaImpresos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\FE_PDF\\")]
        public string CarpetaPDF {
            get {
                return ((string)(this["CarpetaPDF"]));
            }
            set {
                this["CarpetaPDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EscribirEnTabla {
            get {
                return ((bool)(this["EscribirEnTabla"]));
            }
            set {
                this["EscribirEnTabla"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.148\\NETDATASQL;Initial Catalog=NDTEST;User ID=sa;Password=F" +
            "resasc0ncrema;MultipleActiveResultSets=True;Connect Timeout=100;Encrypt=False;Ap" +
            "plication Name=FELCOM;Current Language=spanish")]
        public string cString {
            get {
                return ((string)(this["cString"]));
            }
            set {
                this["cString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UTF8 {
            get {
                return ((bool)(this["UTF8"]));
            }
            set {
                this["UTF8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool imprimir {
            get {
                return ((bool)(this["imprimir"]));
            }
            set {
                this["imprimir"] = value;
            }
        }
    }
}
