'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class activos_maquinas
    Public Property pai_id As Integer
    Public Property emp_id As Integer
    Public Property maq_id As String
    Public Property maq_nombre As String
    Public Property maq_descripcion As String
    Public Property maq_no_serie As String
    Public Property maq_capacidad As String
    Public Property maq_fecha_ingreso As Nullable(Of Date)
    Public Property maq_potencia As Nullable(Of Decimal)
    Public Property mar_id As Nullable(Of Integer)
    Public Property maq_modelo As String
    Public Property cco_id As Nullable(Of Integer)
    Public Property maq_fecha_fabricacion As Nullable(Of Date)
    Public Property maq_dimensiones As String
    Public Property maq_cap_diseno As String
    Public Property ctc_id As String
    Public Property maq_activo_fijo As String
    Public Property maq_peso_neto As Nullable(Of Decimal)
    Public Property maq_fecha_instalacion As Nullable(Of Date)
    Public Property are_id As Nullable(Of Integer)
    Public Property sba_id As Nullable(Of Integer)
    Public Property prv_id As String
    Public Property uni_id As String
    Public Property maq_estado As String
    Public Property maq_manual_fab As String
    Public Property pla_id As Nullable(Of Integer)
    Public Property maq_periodicidad As Nullable(Of Integer)
    Public Property maq_fecha_ult_mantto As Nullable(Of Date)
    Public Property maq_fecha_sig_mantto As Nullable(Of Date)

End Class
