'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cotizacion_capa
    Public Property cot_id As Integer
    Public Property cot_tipo As Nullable(Of Integer)
    Public Property cli_id As String
    Public Property cot_cli_nombre As String
    Public Property cot_cli_nit As String
    Public Property cot_cli_direccion As String
    Public Property cot_cli_telefono As String
    Public Property cot_fecharequerido As Nullable(Of Date)
    Public Property cot_diasvalidez As Nullable(Of Integer)
    Public Property cot_totalcantidad As Nullable(Of Decimal)
    Public Property cot_totalpeso As Nullable(Of Decimal)
    Public Property cot_totalsiva As Nullable(Of Decimal)
    Public Property cot_totalciva As Nullable(Of Decimal)
    Public Property usu_id_crea As Nullable(Of Integer)
    Public Property usu_id_modifica As Nullable(Of Integer)
    Public Property usu_id_autoriza As Nullable(Of Integer)
    Public Property cot_fechacreacion As Nullable(Of Date)
    Public Property cot_fechamodificacion As Nullable(Of Date)
    Public Property cot_fechaautorizacion As Nullable(Of Date)
    Public Property cot_estado As Nullable(Of Integer)
    Public Property cot_keypedido As String
    Public Property cot_clienteregistrado As Nullable(Of Integer)
    Public Property cot_no_paquetes As Nullable(Of Decimal)
    Public Property cot_cli_registrado As Nullable(Of Integer)
    Public Property cot_retencion As Nullable(Of Decimal)
    Public Property cot_percepcion As Nullable(Of Decimal)
    Public Property cot_iva As Nullable(Of Decimal)
    Public Property cot_subtotal As Nullable(Of Decimal)
    Public Property bod_id As String
    Public Property cot_descuento_gral As Nullable(Of Decimal)
    Public Property cot_gravadas As Nullable(Of Decimal)
    Public Property usu_id_fin As Nullable(Of Integer)
    Public Property cot_fechafin As Nullable(Of Date)
    Public Property cot_fechaenvprod As Nullable(Of Date)
    Public Property usu_id_gen_ped_nd As Nullable(Of Integer)
    Public Property cot_fecha_gen_ped_nd As Nullable(Of Date)
    Public Property cot_tipo_doc As String
    Public Property cot_pedido_gen As String
    Public Property emp_id As Nullable(Of Integer)
    Public Property cot_flete As Nullable(Of Decimal)
    Public Property cot_id_canal As String
    Public Property cot_cli_exento As Nullable(Of Boolean)
    Public Property cot_fecha_prorroga As Nullable(Of Date)
    Public Property cot_comentario_prorroga As String
    Public Property cot_exentas As Nullable(Of Decimal)
    Public Property cot_comentario_cancela As String

End Class
