'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cotizacion_detalle
    Public Property cot_id As Integer
    Public Property cot_correlativo As Integer
    Public Property inv_id As String
    Public Property cbo_id As Nullable(Of Integer)
    Public Property cot_descripcion As String
    Public Property cot_cantidad As Nullable(Of Decimal)
    Public Property cot_preciociva As Nullable(Of Decimal)
    Public Property cot_preciosiva As Nullable(Of Decimal)
    Public Property cot_importeciva As Nullable(Of Decimal)
    Public Property cot_importesiva As Nullable(Of Decimal)
    Public Property cot_peso As Nullable(Of Decimal)
    Public Property cot_margen As Nullable(Of Decimal)
    Public Property cot_costoproduccion As Nullable(Of Decimal)
    Public Property usu_id_autorizadaprecio As Nullable(Of Integer)
    Public Property cot_fechaautorizacion As Nullable(Of Date)
    Public Property cot_precioautorizado As Nullable(Of Decimal)
    Public Property scp_id As Nullable(Of Integer)
    Public Property ran_pesodesde As Nullable(Of Decimal)
    Public Property ran_pesohasta As Nullable(Of Decimal)
    Public Property ran_valor As Nullable(Of Decimal)
    Public Property cot_existeinventario As Nullable(Of Boolean)
    Public Property cot_req_auto_precio As Nullable(Of Boolean)
    Public Property cot_origenprecio As String
    Public Property inv_unidadpresentacion As Nullable(Of Integer)
    Public Property cot_costo_unitario_mo As Nullable(Of Decimal)
    Public Property cot_costo_unitario As Nullable(Of Decimal)
    Public Property cot_precio_sugerido As Nullable(Of Decimal)
    Public Property cot_estado As Nullable(Of Integer)
    Public Property cot_estado_aut_precio As String
    Public Property cot_key_pedido As String
    Public Property cot_inv_prorrateado As Nullable(Of Boolean)
    Public Property cot_valor_prorrateo_siva As Nullable(Of Decimal)
    Public Property cot_valor_prorrateo_siva_uni As Nullable(Of Decimal)
    Public Property cot_precio_final_siva As Nullable(Of Decimal)
    Public Property cot_precio_final_civa As Nullable(Of Decimal)
    Public Property cot_total_final_civa As Nullable(Of Decimal)
    Public Property cot_total_final_siva As Nullable(Of Decimal)
    Public Property cot_und_paq As Nullable(Of Integer)
    Public Property cot_det_insumo As Nullable(Of Integer)

End Class
