'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class general_documentos_correlativos
    Public Property pai_id As Integer
    Public Property emp_id As Integer
    Public Property doc_serie As String
    Public Property doc_id As String
    Public Property doc_correlativo As Nullable(Of Integer)
    Public Property doc_estado As String
    Public Property usu_id_crea As Nullable(Of Integer)
    Public Property usu_id_modifica As Nullable(Of Integer)
    Public Property doc_fecha_hora_creacion As Nullable(Of Date)
    Public Property doc_fecha_hora_modificacion As Nullable(Of Date)

End Class
