'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class general_plantas
    Public Property pai_id As Integer
    Public Property emp_id As Integer
    Public Property pla_id As Integer
    Public Property cco_id As Nullable(Of Integer)
    Public Property pla_descripcion As String

End Class
