'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class general_empresas
    Public Property pai_id As Integer
    Public Property emp_id As Integer
    Public Property emp_nombre As String
    Public Property emp_nombre_corto As String
    Public Property usu_id_crea As Nullable(Of Integer)
    Public Property usu_id_modifica As Nullable(Of Integer)
    Public Property emp_fecha_hora_creacion As Nullable(Of Date)
    Public Property emp_fecha_hora_modificacion As Nullable(Of Date)
    Public Property cli_id_rel As String
    Public Property prv_id_rel As String
    Public Property emp_direccion As String
    Public Property emp_nombre_banco As String
    Public Property emp_tipo_cuenta As String
    Public Property emp_no_cuenta As String

End Class
