'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class general_areas
    Public Property pai_id As Integer
    Public Property emp_id As Integer
    Public Property are_id As Integer
    Public Property cco_id As Nullable(Of Integer)
    Public Property are_descripcion As String
    Public Property ctc_id As String
    Public Property are_activo As Nullable(Of Boolean)
    Public Property are_fecha_hora_creacion As Nullable(Of Date)
    Public Property usu_id_crea As Nullable(Of Integer)
    Public Property are_fecha_hora_modificacion As Nullable(Of Date)
    Public Property usu_id_modifica As Nullable(Of Integer)
    Public Property pla_id As Nullable(Of Integer)

End Class
