'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class GlobalDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=GlobalDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property general_areas() As DbSet(Of general_areas)
    Public Overridable Property general_sub_areas() As DbSet(Of general_sub_areas)
    Public Overridable Property mantto_orden_capa() As DbSet(Of mantto_orden_capa)
    Public Overridable Property mantto_orden_centros_atencion() As DbSet(Of mantto_orden_centros_atencion)
    Public Overridable Property mantto_orden_prioridades() As DbSet(Of mantto_orden_prioridades)
    Public Overridable Property mantto_orden_tipos() As DbSet(Of mantto_orden_tipos)
    Public Overridable Property usuario_usuarios() As DbSet(Of usuario_usuarios)
    Public Overridable Property general_paises() As DbSet(Of general_paises)
    Public Overridable Property general_empresas() As DbSet(Of general_empresas)
    Public Overridable Property v_usuario_empresa() As DbSet(Of v_usuario_empresa)
    Public Overridable Property general_documentos_correlativos() As DbSet(Of general_documentos_correlativos)
    Public Overridable Property activos_maquinas() As DbSet(Of activos_maquinas)
    Public Overridable Property v_tablero_app() As DbSet(Of v_tablero_app)
    Public Overridable Property mantto_orden_items() As DbSet(Of mantto_orden_items)
    Public Overridable Property usuario_empresa_usuario() As DbSet(Of usuario_empresa_usuario)
    Public Overridable Property general_plantas() As DbSet(Of general_plantas)
    Public Overridable Property v_usuario_empresa_plantel() As DbSet(Of v_usuario_empresa_plantel)
    Public Overridable Property inventario_inventarios() As DbSet(Of inventario_inventarios)
    Public Overridable Property general_unidades_medida() As DbSet(Of general_unidades_medida)
    Public Overridable Property mantto_orden_estados() As DbSet(Of mantto_orden_estados)
    Public Overridable Property notificaciones_push() As DbSet(Of notificaciones_push)
    Public Overridable Property v_ordenes_asignadas() As DbSet(Of v_ordenes_asignadas)
    Public Overridable Property v_ordenes_mantto() As DbSet(Of v_ordenes_mantto)
    Public Overridable Property v_estados_ordenes() As DbSet(Of v_estados_ordenes)
    Public Overridable Property v_mecanicos_orden_mantto() As DbSet(Of v_mecanicos_orden_mantto)
    Public Overridable Property mantto_orden_mano_obra() As DbSet(Of mantto_orden_mano_obra)
    Public Overridable Property v_listado_mecanicos() As DbSet(Of v_listado_mecanicos)
    Public Overridable Property v_usuario_nomina() As DbSet(Of v_usuario_nomina)
    Public Overridable Property v_usuario_usuarios() As DbSet(Of v_usuario_usuarios)
    Public Overridable Property menu_asignaciones() As DbSet(Of menu_asignaciones)
    Public Overridable Property menu_submenu() As DbSet(Of menu_submenu)
    Public Overridable Property cotizacion_detalle() As DbSet(Of cotizacion_detalle)
    Public Overridable Property cotizacion_capa() As DbSet(Of cotizacion_capa)

End Class
