'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class inventario_inventarios
    Public Property pai_id As Integer
    Public Property inv_id As String
    Public Property inv_descripcion As String
    Public Property inv_descripcion_larga As String
    Public Property mar_id As Nullable(Of Integer)
    Public Property inv_modelo As String
    Public Property uni_id As String
    Public Property inv_kit As Nullable(Of Boolean)
    Public Property inv_tipo As String
    Public Property inv_cod_barra As String
    Public Property cla_id As Nullable(Of Integer)
    Public Property lin_id As Nullable(Of Integer)
    Public Property sbl_id As Nullable(Of Integer)
    Public Property inv_maneja_existencias As Nullable(Of Boolean)
    Public Property inv_imagen As String
    Public Property inv_peso As Nullable(Of Decimal)
    Public Property inv_estado As String
    Public Property inv_otros_datos As String
    Public Property inv_unidad_presentacion As Nullable(Of Integer)
    Public Property ctc_id As String
    Public Property ctc_id_venta As String
    Public Property ctc_id_rebaja As String
    Public Property ctc_id_descuento As String
    Public Property ctc_id_requisicion As String
    Public Property ctc_id_prod_proceso As String
    Public Property ctc_id_devolucion As String
    Public Property ctc_id_costo_venta As String
    Public Property ctc_id_pedido_transito As String
    Public Property usu_id_crea As Nullable(Of Integer)
    Public Property usu_id_modifica As Nullable(Of Integer)
    Public Property inv_fecha_hora_creacion As Nullable(Of Date)
    Public Property inv_fecha_hora_modificacion As Nullable(Of Date)
    Public Property inv_cod_fabrica As String
    Public Property inv_fecha_hora_sincronizacion As Nullable(Of Date)
    Public Property prv_id As String

End Class
