'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mantto_orden_capa
    Public Property pai_id As Integer
    Public Property emp_id As Integer
    Public Property ord_id As Integer
    Public Property tio_id As Nullable(Of Integer)
    Public Property pla_id As Nullable(Of Integer)
    Public Property are_id As Nullable(Of Integer)
    Public Property sba_id As Nullable(Of Integer)
    Public Property pri_id As Nullable(Of Integer)
    Public Property maq_id As String
    Public Property mec_id_responsable As Nullable(Of Integer)
    Public Property oes_id As Nullable(Of Integer)
    Public Property usu_id_crea As Nullable(Of Integer)
    Public Property usu_id_modifica As Nullable(Of Integer)
    Public Property ord_fecha_hora_creacion As Nullable(Of Date)
    Public Property ord_fecha_hora_modificacion As Nullable(Of Date)
    Public Property ord_fecha_programado As Nullable(Of Date)
    Public Property ord_fecha_hora_inicio As Nullable(Of Date)
    Public Property ord_fecha_hora_fin As Nullable(Of Date)
    Public Property ord_descripcion As String
    Public Property ord_horas_hombre_estimada As Nullable(Of Decimal)
    Public Property ord_fecha_hora_cierre_orden As Nullable(Of Date)
    Public Property ord_calificacion As Nullable(Of Integer)
    Public Property ord_comentarios_cierre As String
    Public Property ord_id_padre As Nullable(Of Integer)
    Public Property ord_descripcion_falla As String
    Public Property ord_causa_falla As String
    Public Property ord_accion_correctiva As String
    Public Property ord_fecha_hora_peticion_materiales As Nullable(Of Date)
    Public Property ord_fecha_hora_entrega_materiales As Nullable(Of Date)
    Public Property cda_id As Nullable(Of Integer)
    Public Property ord_comentarios_mecanico As String
    Public Property ord_causa_especial As Nullable(Of Integer)
    Public Property ord_comen_causa_especial As String

End Class
