'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mantto_orden_items
    Public Property pai_id As Integer
    Public Property emp_id As Integer
    Public Property ord_id As Integer
    Public Property dor_id As Integer
    Public Property inv_id As String
    Public Property dor_descripcion As String
    Public Property dor_cantidad As Nullable(Of Decimal)
    Public Property dor_unitario As Nullable(Of Decimal)
    Public Property dor_costo As Nullable(Of Decimal)
    Public Property dor_importe As Nullable(Of Decimal)
    Public Property usu_id_crea As Nullable(Of Integer)
    Public Property usu_id_modifica As Nullable(Of Integer)
    Public Property dor_fecha_hora_creacion As Nullable(Of Date)
    Public Property dor_fecha_hora_modificacion As Nullable(Of Date)
    Public Property dor_tipo As String
    Public Property reg_id As Integer
    Public Property dor_estado As Nullable(Of Integer)
    Public Property dor_descripcion_larga As String

End Class
