'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mantto_orden_prioridades
    Public Property pri_id As Integer
    Public Property pri_descripcion As String
    Public Property pri_nivel As Nullable(Of Integer)
    Public Property usu_id_crea As Nullable(Of Integer)
    Public Property usu_id_modifica As Nullable(Of Integer)
    Public Property pri_fecha_hora_creacion As Nullable(Of Date)
    Public Property pri_fecha_hora_modificacion As Nullable(Of Date)
    Public Property pri_clase As String

End Class
