'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mantto_orden_mano_obra
    Public Property pai_id As Integer
    Public Property emp_id As Integer
    Public Property ord_id As Integer
    Public Property mod_id As Integer
    Public Property mod_estado As String
    Public Property mec_id As Nullable(Of Integer)
    Public Property usu_id_nomina As String
    Public Property mod_fecha_hora_inicio As Nullable(Of Date)
    Public Property mod_fecha_hora_fin As Nullable(Of Date)
    Public Property mod_costo_por_hora As Nullable(Of Decimal)
    Public Property mod_total_costo As Nullable(Of Decimal)
    Public Property mod_comentarios As String
    Public Property mod_fecha_hora_creacion As Nullable(Of Date)
    Public Property mod_fecha_hora_modificacion As Nullable(Of Date)
    Public Property usu_id_crea As Nullable(Of Integer)
    Public Property usu_id_modifica As Nullable(Of Integer)
    Public Property mod_nombre_mecanico As String
    Public Property mod_externo As Nullable(Of Boolean)

End Class
