'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class menu_asignaciones
    Public Property men_id As Integer
    Public Property sub_id As Integer
    Public Property usu_id As Integer
    Public Property asi_insertar As Nullable(Of Integer)
    Public Property asi_borrar As Nullable(Of Integer)
    Public Property asi_modificar As Nullable(Of Integer)

End Class
