'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class menu_submenu
    Public Property sub_id As Integer
    Public Property men_id As Integer
    Public Property sub_descripcion As String
    Public Property sub_icon As String
    Public Property sub_funcion As String
    Public Property sub_orden As Nullable(Of Integer)

End Class
