'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class notificaciones_push
    Public Property pus_id As Long
    Public Property pai_id As Nullable(Of Integer)
    Public Property emp_id As Nullable(Of Integer)
    Public Property ord_id As Nullable(Of Integer)
    Public Property usu_id As Nullable(Of Integer)
    Public Property pus_read As Nullable(Of Boolean)
    Public Property pus_fecha As Nullable(Of Date)
    Public Property pus_title As String
    Public Property pus_descripcion As String

End Class
