'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class usuario_empresa_usuario
    Public Property pai_id As Integer
    Public Property emp_id As Integer
    Public Property usu_id As Integer
    Public Property suc_id As String
    Public Property bod_id As String
    Public Property pla_id As Nullable(Of Integer)

End Class
