'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_estados_ordenes
    Public Property oes_id As Integer
    Public Property oes_descripcion As String
    Public Property estado_color As String
    Public Property avance As Nullable(Of Decimal)
    Public Property oes_descripcion2 As String

End Class
