'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_listado_mecanicos
    Public Property mec_id As Integer
    Public Property mec_nombre As String
    Public Property usu_nomina_fotografia As String
    Public Property mec_estado As String
    Public Property mec_estado_color As String
    Public Property ordenes_asignadas As String

End Class
