'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_mecanicos_orden_mantto
    Public Property pai_id As Integer
    Public Property emp_id As Integer
    Public Property ord_id As Integer
    Public Property mod_id As Integer
    Public Property mec_id As Nullable(Of Integer)
    Public Property mec_nombre As String
    Public Property mec_telefono As String
    Public Property usu_nomina_fotografia As String

End Class
