'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_ordenes_asignadas
    Public Property pai_id As Integer
    Public Property emp_id As Integer
    Public Property ord_id As Integer
    Public Property ord_fecha_hora_creacion As Nullable(Of Date)
    Public Property oes_descripcion As String
    Public Property mec_id As Integer
    Public Property mec_nombres As String
    Public Property usu_id_crea As Nullable(Of Integer)
    Public Property usu_nombres As String
    Public Property usu_nomina_fotografia As String
    Public Property usu_id_mec As Nullable(Of Integer)
    Public Property ord_descripcion As String
    Public Property estado_color As String
    Public Property detalle As String
    Public Property are_descripcion As String
    Public Property sba_descripcion As String
    Public Property maq_descripcion As String
    Public Property maq_nombre As String
    Public Property maq_id As String
    Public Property no_materiales As Integer
    Public Property no_mecanicos As Integer
    Public Property color_prioridad As String
    Public Property avance As Nullable(Of Decimal)
    Public Property pla_id As Nullable(Of Integer)
    Public Property pri_descripcion As String
    Public Property tio_descripcion As String
    Public Property ord_comentarios_mecanico As String

End Class
