'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_ordenes_mantto
    Public Property pai_id As Integer
    Public Property emp_id As Integer
    Public Property ord_id As Integer
    Public Property tio_descripcion As String
    Public Property pla_id As Nullable(Of Integer)
    Public Property pla_descripcion As String
    Public Property usu_id_crea As Nullable(Of Integer)
    Public Property ord_fecha_hora_creacion As Nullable(Of Date)
    Public Property are_id As Nullable(Of Integer)
    Public Property are_descripcion As String
    Public Property sba_id As Nullable(Of Integer)
    Public Property sba_descripcion As String
    Public Property maq_id As String
    Public Property maq_nombre As String
    Public Property pri_id As Nullable(Of Integer)
    Public Property pri_descripcion As String
    Public Property color_prioridad As String
    Public Property avance As Nullable(Of Decimal)
    Public Property estado_color As String
    Public Property oes_id As Nullable(Of Integer)
    Public Property oes_descripcion As String
    Public Property ord_descripcion As String
    Public Property mecanicos_asignados As Integer
    Public Property usu_nomina_fotografia As String
    Public Property ord_descripcion_2 As String
    Public Property detalle As String

End Class
