'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_tablero_app
    Public Property usu_id As Integer
    Public Property t_ord_ejecusion As Nullable(Of Integer)
    Public Property t_creadas_hoy As Nullable(Of Integer)
    Public Property t_creadas_anio As Nullable(Of Integer)
    Public Property t_asignadas_hoy As Nullable(Of Integer)
    Public Property t_asingadas_anio As Nullable(Of Integer)
    Public Property t_asignar_hoy As Nullable(Of Integer)
    Public Property t_asignar_anio As Nullable(Of Integer)
    Public Property t_historial_hoy As Nullable(Of Integer)
    Public Property t_historial_anio As Nullable(Of Integer)

End Class
