'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_usuario_usuarios
    Public Property usu_id As Integer
    Public Property dep_id As Nullable(Of Integer)
    Public Property car_id As Nullable(Of Integer)
    Public Property est_id As Nullable(Of Integer)
    Public Property usu_username As String
    Public Property usu_password As Byte()
    Public Property usu_nombres As String
    Public Property usu_apellidos As String
    Public Property usu_genero As String
    Public Property usu_correo As String
    Public Property usu_telefono As String
    Public Property usu_id_nomina As String
    Public Property usu_direccion As String
    Public Property usu_fecha_registro As Nullable(Of Date)
    Public Property usu_fecha_nacimiento As Nullable(Of Date)
    Public Property usu_ultima_conexion As Nullable(Of Date)
    Public Property usu_cambiar_pass As Nullable(Of Short)
    Public Property usu_ver_all As Nullable(Of Integer)
    Public Property es_mecanico As Nullable(Of Boolean)

End Class
