'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_usuario_nomina
    Public Property usu_id_nomina As String
    Public Property usu_nomina_nombre As String
    Public Property usu_nomina_fotografia As String
    Public Property FechaIngreso As Date
    Public Property Nombre_Gerencia As String
    Public Property Dealer As Integer
    Public Property usu_id_nomina2 As String
    Public Property Cargo As String

End Class
