'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ModuloTelefonos_Equipos
    Public Property id_equipo As Integer
    Public Property id_tipo As Nullable(Of Integer)
    Public Property id_marca As Nullable(Of Integer)
    Public Property serie As String
    Public Property modelo As String
    Public Property descripcion As String
    Public Property estado As String
    Public Property fecha_compra As Nullable(Of Date)
    Public Property proveedor As String
    Public Property tiempo_garantia_meses As Nullable(Of Integer)
    Public Property id_estado As Nullable(Of Integer)
    Public Property disponible As Nullable(Of Boolean)

End Class
