'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ModuloTelefonosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ModuloTelefonosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ModuloTelefonos_Equipos_Tipos() As DbSet(Of ModuloTelefonos_Equipos_Tipos)
    Public Overridable Property marcas() As DbSet(Of marcas)
    Public Overridable Property estados() As DbSet(Of estados)
    Public Overridable Property ModuloTelefonos_Equipos() As DbSet(Of ModuloTelefonos_Equipos)
    Public Overridable Property v_ModuloTelefonos_Equipos() As DbSet(Of v_ModuloTelefonos_Equipos)

End Class
